
import { BasicState } from '../elementa/state'
import { type Color, hex } from '../elementa/color'

const SLOTS = [
  'primary',
  'componentBorderDark',
  'midGray',
  'button',
  'buttonHighlight',
  'text',
  'textHighlight',
  'textDisabled',
  'textWarning',
  'textShadow',
  'textShadowLight',
  'textShadowMid',
  'componentBackground',
  'componentBackgroundHighlight',
  'componentBorder',
  'componentHighlight',
  'dividerDark',
  'scrollbar',
  'mainBackground',
  'textActive',
  'textActiveShadow',
  'tierCommon',
  'tierUncommon',
  'tierRare',
  'tierEpic',
  'tierLegendary',
  'navEmotes',
  'navCosmetics',
] as const

export type PaletteSlot = (typeof SLOTS)[number]
export type Palette = Record<PaletteSlot, BasicState<Color>>
export type ThemeDefinition = { name: string } & Record<PaletteSlot, string>

export const VIGILANCE: ThemeDefinition = {
  name: 'Vigilance',
  primary: '#2997FF',
  componentBorderDark: '#000000',
  midGray: '#939393',
  button: '#323232',
  buttonHighlight: '#474747',
  text: '#BBBBBB',
  textHighlight: '#FFFFFF',
  textDisabled: '#6A6A6A',
  textWarning: '#F5534F',
  textShadow: '#161618',
  textShadowLight: '#3F3F3F',
  textShadowMid: '#232323',
  componentBackground: '#232323',
  componentBackgroundHighlight: '#2F2F2F',
  componentBorder: '#474747',
  componentHighlight: '#303030',
  dividerDark: '#232323',
  scrollbar: '#545454',
  mainBackground: '#181818',
  textActive: '#2997FF',
  textActiveShadow: '#0A253F',
  tierCommon: '#939393',
  tierUncommon: '#5FD18C',
  tierRare: '#2997FF',
  tierEpic: '#B06CFF',
  tierLegendary: '#FFB02E',
  navEmotes: '#FFD84D',
  navCosmetics: '#FF9B3D',
}

export const LIGHT: ThemeDefinition = {
  ...VIGILANCE,
  name: 'Paper',
  primary: '#3A76C4',
  midGray: '#8A8578',
  button: '#E4DFD3',
  buttonHighlight: '#D8D2C4',
  text: '#4A4740',
  textHighlight: '#2B2924',
  textDisabled: '#9B968A',
  textWarning: '#C2564F',
  textShadow: '#FFFFFF',
  textShadowLight: '#FFFFFF',
  textShadowMid: '#EDE8DC',
  componentBackground: '#EDE8DC',
  componentBackgroundHighlight: '#E4DFD3',
  componentBorder: '#CFC9BA',
  componentHighlight: '#E0DACC',
  dividerDark: '#DDD7C9',
  scrollbar: '#BFB9AA',
  mainBackground: '#F6F2E9',
  textActive: '#3A76C4',
  textActiveShadow: '#C9D9EE',
  tierCommon: '#8A8578',
  tierUncommon: '#3F9E63',
  tierRare: '#3A76C4',
  tierEpic: '#8A5BC4',
  tierLegendary: '#C58A2E',
  navEmotes: '#C79A28',
  navCosmetics: '#C46F2E',
}

export const DRACULA: ThemeDefinition = {
  ...VIGILANCE,
  name: 'Dracula',
  primary: '#BD93F9',
  midGray: '#6272A4',
  button: '#44475A',
  buttonHighlight: '#565A71',
  text: '#C3C8DE',
  textHighlight: '#F8F8F2',
  textDisabled: '#6272A4',
  textWarning: '#FF5555',
  textShadow: '#191A21',
  textShadowLight: '#44475A',
  textShadowMid: '#21222C',
  componentBackground: '#282A36',
  componentBackgroundHighlight: '#343746',
  componentBorder: '#44475A',
  componentHighlight: '#343746',
  dividerDark: '#21222C',
  scrollbar: '#6272A4',
  mainBackground: '#1E1F29',
  textActive: '#BD93F9',
  textActiveShadow: '#2E2440',
  tierCommon: '#6272A4',
  tierUncommon: '#50FA7B',
  tierRare: '#8BE9FD',
  tierEpic: '#BD93F9',
  tierLegendary: '#F1FA8C',
  navEmotes: '#F1FA8C',
  navCosmetics: '#FFB86C',
}

export const MOCHA: ThemeDefinition = {
  ...VIGILANCE,
  name: 'Mocha',
  primary: '#89B4FA',
  midGray: '#6C7086',
  button: '#313244',
  buttonHighlight: '#45475A',
  text: '#BAC2DE',
  textHighlight: '#CDD6F4',
  textDisabled: '#6C7086',
  textWarning: '#F38BA8',
  textShadow: '#11111B',
  textShadowLight: '#45475A',
  textShadowMid: '#181825',
  componentBackground: '#1E1E2E',
  componentBackgroundHighlight: '#313244',
  componentBorder: '#45475A',
  componentHighlight: '#313244',
  dividerDark: '#181825',
  scrollbar: '#585B70',
  mainBackground: '#11111B',
  textActive: '#89B4FA',
  textActiveShadow: '#1E2A45',
  tierCommon: '#9399B2',
  tierUncommon: '#A6E3A1',
  tierRare: '#89B4FA',
  tierEpic: '#CBA6F7',
  tierLegendary: '#F9E2AF',
  navEmotes: '#F9E2AF',
  navCosmetics: '#FAB387',
}

export const NORD: ThemeDefinition = {
  ...VIGILANCE,
  name: 'Nord',
  primary: '#88C0D0',
  midGray: '#4C566A',
  button: '#3B4252',
  buttonHighlight: '#434C5E',
  text: '#D8DEE9',
  textHighlight: '#ECEFF4',
  textDisabled: '#6B7488',
  textWarning: '#BF616A',
  textShadow: '#20242C',
  textShadowLight: '#434C5E',
  textShadowMid: '#2E3440',
  componentBackground: '#2E3440',
  componentBackgroundHighlight: '#3B4252',
  componentBorder: '#434C5E',
  componentHighlight: '#3B4252',
  dividerDark: '#2A2F3A',
  scrollbar: '#4C566A',
  mainBackground: '#242933',
  textActive: '#88C0D0',
  textActiveShadow: '#22333B',
  tierCommon: '#7B849B',
  tierUncommon: '#A3BE8C',
  tierRare: '#81A1C1',
  tierEpic: '#B48EAD',
  tierLegendary: '#EBCB8B',
  navEmotes: '#EBCB8B',
  navCosmetics: '#D08770',
}

export const EMBER: ThemeDefinition = {
  ...VIGILANCE,
  name: 'Ember',
  primary: '#FF7A3D',
  midGray: '#C9A294',
  button: '#3A241E',
  buttonHighlight: '#4A2D26',
  text: '#E8D2C7',
  textHighlight: '#FFF3EC',
  textDisabled: '#7D5C50',
  textShadow: '#140D0B',
  textShadowLight: '#4A2D26',
  textShadowMid: '#241816',
  componentBackground: '#241816',
  componentBackgroundHighlight: '#33201C',
  componentBorder: '#6B3D31',
  componentHighlight: '#331F1A',
  dividerDark: '#241816',
  scrollbar: '#6B3D31',
  mainBackground: '#1B1210',
  textActive: '#FF7A3D',
  textActiveShadow: '#3F1B0A',
  tierRare: '#4DC0FF',
  tierEpic: '#E07AFF',
}

export const THEMES: ThemeDefinition[] = [VIGILANCE, DRACULA, MOCHA, NORD, EMBER, LIGHT]

export function createPalette(theme: ThemeDefinition = VIGILANCE): Palette {
  return Object.fromEntries(SLOTS.map((slot) => [slot, new BasicState(hex(theme[slot]))])) as Palette
}

export function applyTheme(palette: Palette, theme: ThemeDefinition): void {
  for (const slot of SLOTS) palette[slot].set(hex(theme[slot]))
}

export const PALETTE_SLOTS = SLOTS
